# This file should stay pretty static.
# The 'version' is updated when the package is created.
# See release.mk - build/helm target.
apiVersion: v2
name: coder
description: >
  Coder moves developer workspaces to your cloud and centralizes their
  creation and management.
appVersion: 1.28.0
version: 1.28.0
# Coder has a hard requirement on Kubernetes 1.19, as this version
# introduced the networking.k8s.io/v1 API for the Ingress and
# NetworkPolicy resources.
#
# Additionally, the NOTES.txt file emits a warning if the cluster
# version is outside our soft requirement, in accordance with our
# official support policy.
kubeVersion: ">= 1.19.0-0"
home: https://coder.com
keywords:
  - coder
sources:
  - https://github.com/cdr/enterprise-helm
icon: https://helm.coder.com/coder_logo_black.png
maintainers:
  - name: Coder Technologies, Inc.
    email: support@coder.com
    url: https://coder.com/contact
