coderd:
  replicas: 1
  serviceSpec:
    # Avoid provisioning a LoadBalancer
    type: ClusterIP

  # Reduce resource requirements for deployments using kind, which
  # we typically use for development and test purposes only.
  resources:
    requests:
      memory: "32Mi"

postgres:
  default:
    # Reduce resource requirements for deployments using kind, which
    # we typically use for development and test purposes only.
    resources:
      requests:
        memory: "32Mi"
