coderd:
  serviceSpec:
    type: ClusterIP
  replicas: 1
  resources:
    requests:
      cpu: "0m"
      memory: "32Mi"
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    seccompProfile:
      type: RuntimeDefault
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000

postgres:
  default:
    resources:
      requests:
        cpu: "0m"
        memory: "32Mi"
