coderd:
  devurlsHost: '*.devurls.coderhost.com'
  serviceSpec:
    # The Ingress will route traffic to the internal ClusterIP.
    type: ClusterIP
    externalTrafficPolicy: ""

ingress:
  enable: true
  # Hostname to use for routing decisions
  host: 'coder.coderhost.com'
  # Custom annotations to apply to the resulting Ingress object.
  # This is useful for configuring other controllers in the cluster,
  # such as cert-manager or the ingress controller.
  annotations: {}
