{{- if not .Values.coderd.satellite.enable }}
---
# The service account that the envproxy passes to cemanager on startup.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: coder
  namespace: {{ .Release.Namespace | quote }}
  annotations:
  {{- range $key, $value := fromYaml (include "movedValue" (dict "Values" .Values "Key" "coderd.builtinProviderServiceAccount.annotations")) }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  labels:
  {{- range $key, $value := fromYaml (include "movedValue" (dict "Values" .Values "Key" "coderd.builtinProviderServiceAccount.labels")) }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: coder
  namespace: {{ .Release.Namespace | quote }}
rules:
  - apiGroups: ["", "apps", "networking.k8s.io"] # "" indicates the core API group
    resources: ["persistentvolumeclaims", "pods", "deployments", "services", "secrets", "pods/exec","pods/log", "events", "networkpolicies"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete", "deletecollection"]
  - apiGroups: ["metrics.k8s.io", "storage.k8s.io"]
    resources: ["pods", "storageclasses"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: coder
  namespace: {{ .Release.Namespace | quote }}
subjects:
  - kind: ServiceAccount
    name: coder
roleRef:
  kind: Role
  name: coder
  apiGroup: rbac.authorization.k8s.io
{{- end }}