name: fuzz

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

# Cancel in-progress runs for pull requests when developers push
# additional changes, and serialize builds in branches.
# https://docs.github.com/en/actions/using-jobs/using-concurrency#example-using-concurrency-to-cancel-any-in-progress-job-or-run
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  fuzz:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.17"

      - name: Fuzz
        run: go test -run ^TestFuzz$ cdr.dev/enterprise-helm/tests -count=1000
        working-directory: tests
