name: fuzz

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  fuzz:
    runs-on: ubuntu-20.04
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1
        if: github.event_type == 'pull_request'

      - name: Checkout source
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.17"

      - name: Fuzz
        run: go test -run ^TestFuzz$ cdr.dev/enterprise-helm/tests -count=1000
        working-directory: tests
